### ISSUE TITLE
pyasn1 version requirement 'pyasn1==0.3.1,<=0.4.8' causes dependency resolution problems

### ISSUE THREAD

**Issue by jprodriguez-nbs** [PelionIoT/manifest-tool#23]
requirements file has 

pyasn1==0.3.1,<=0.4.8

This creates dependency resolution problems and seems incorrect. 
It looks like the correct line would be:

pyasn1>=0.3.1,<=0.4.8

**Comment by moshe-shahar** [comment]
Thanks @jprodriguez-nbs.
The fix will be integrated into the next release.

**Comment by moshe-shahar** [comment]
@jprodriguez-nbs ,
The fix was released as part of [v2.2.0](https://github.com/PelionIoT/manifest-tool/blob/v2.2.0/requirements.txt#L5) release.
