### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [PelionIoT/manifest-tool#31]
Problem
---------
On aarch64, ‘pip install manifest-tool’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install manifest-tool’ should download the wheels from pypi

@moshe-shahar and Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by JanneKiiskila** [comment]
https://github.com/PelionIoT/manifest-tool/pull/32 - fixed this, closing issue.
