### ISSUE TITLE
v1.4.8 - Pip install fails - missing requirements.txt

### ISSUE THREAD

**Issue by bentcooke** [PelionIoT/manifest-tool#6]
When trying to install or upgrade to v1.4.8, Pip install manifest-tool fails with:
`Collecting manifest-tool
  Using cached https://files.pythonhosted.org/packages/61/00/fb183d44ad303ef3462f04398a94c8ce09ba049000f616c630d1e83bb07c/manifest-tool-1.4.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2zsjtx/manifest-tool/setup.py", line 34, in <module>
        reqs = [str(r.req) for r in install_reqs]
      File "/proj/ben/testvenv/local/lib/python2.7/site-packages/pip/_internal/req/req_file.py", line 82, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/proj/ben/testvenv/local/lib/python2.7/site-packages/pip/_internal/download.py", line 440, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip._internal.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
`
I have tested this in and out of a venv using python 2.7.13.  pip installing from git does work though.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTUC-840

**Comment by cmonr** [comment]
Curious. What are your versions of `pip` and `setuptools`?

Could you also provide the output of `pip list --verbose`?

**Comment by bentcooke** [comment]
Here you go:

Package    Version Location                                       Installer
---------- ------- ---------------------------------------------- ---------
pip        18.1    /proj/ben/testvenv/lib/python2.7/site-packages pip
setuptools 40.6.3  /proj/ben/testvenv/lib/python2.7/site-packages pip
wheel      0.32.3  /proj/ben/testvenv/lib/python2.7/site-packages pip
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by orenc17** [comment]
@bentcooke could you please check with the latest version?

**Comment by cmonr** [comment]
This is probably safe to close as resolved.

**Comment by moshe-shahar** [comment]
Please use the latest version.
